apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-runner-#{DEPLOYMENT}#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gh-runner-#{DEPLOYMENT}#
  template:
    metadata:
      labels:
        app: gh-runner-#{DEPLOYMENT}#
    spec:
      serviceAccountName: deployment-manager
      containers:
        - name: gh-runner-#{DEPLOYMENT}#
          image: mioherman/github-runner:arm64
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: kubeconfig
              mountPath: /root/.kube
              subPath: config
          env:
            - name: REPO_URL
              value: #{REPO_URL}#
            - name: RUNNER_NAME
              value: arm64
            - name: ACCESS_TOKEN
              value: #{ACCESS_TOKEN}#
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: kubeconfig
          configMap:
            name: kubeconfig-cm
