name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  # Start the self-hosted runner
  start-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/runner.yml"]'
        env:
          REPO_URL: https://github.com/${{ github.repository }}
          RUNNER_NAME: ${{ github.repository }}
          DEPLOYMENT: ${{ github.repository }}
          ACCESS_TOKEN: ${{ secrets.RUNNER_ACCESS_TOKEN }}

      - name: Trigger deploy
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f deploy/runner.yml
  
  # Build and push the docker image
  push_to_registry:
    needs: start-runner
    name: Build and push image
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: rpi2.null.care
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            rpi2.null.care/knbn-ui
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            rpi2.null.care/knbn-ui:latest
          
  # Deploy to kubernetes        
  deploy:
    needs: push_to_registry
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: kubectl apply
        run: kubernetes-rollout

  # Stop the self-hosted runner
  stop-runner:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: delete deployment/github-runner-${{ github.run_id }}
