name: CI

on:
  push:
    branches: [ "main" ]

jobs:
# Build and push the docker image
  push_to_registry:
    name: Push Docker image to registry
    runs-on: ARM64
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: rpi2.null.care
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            rpi2.null.care/knbn-ui
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            rpi2.null.care/knbn-ui:latest
          
  # Deploy to kubernetes        
  deploy:
    needs: push_to_registry
    runs-on: ARM64
    steps:
      - uses: actions/checkout@v3
      - name: kubectl apply
        run: kubernetes-rollout
