name: Check Self-hosted Runners

on:
  workflow_dispatch:

jobs:
  check-runners:
    runs-on: ubuntu-latest

    steps:
      - name: List Runners
        timeout-minutes: 1
        id: runners
        run: |
          runners=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runners")

          echo "::set-output name=runners::${runners}"

      - name: Display Runners
        run: echo "${{ steps.runners.outputs.runners }}"
