name: Check self-hosted runner

on:
  workflow_dispatch:

jobs:
  job1:
    name: Check Runner
    runs-on: [self-hosted, ubuntu-latest]
    timeout-minutes: 1
    steps:
      - name: Echo out the input variables
        run: |
          echo "${{ runner.name }}"
