name: Check self-hosted runner

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Replace tokens
      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/runner.yml"]'
        env:
          REPO_URL: https://github.com/${{ github.repository }}
          RUNNER_NAME: ${{ github.repository }}
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger deploy
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply deploy/runner.yml
